forgejo:
  image:
    repository: 212757224597.dkr.ecr.eu-central-1.amazonaws.com/forgejo
    tag: latest     
    pullPolicy: Always

  replicas: 2

  service:
    name: forgejo-app-service
    type: LoadBalancer
    port: 3000

  ingress:
    enabled: false  # AWS LoadBalancer
    host: forgejo.local
    path: /

  config:
    appName: "Forgejo"
    httpPort: "3000"
    rootUrl:
    domain:
    sshDomain:
    httpAddr: "0.0.0.0"
    dbType: "postgres"
    dbHost:
    dbPort:
    dbName:

  credentials:
    secretName: forgejo-secret
    dbUser:
    dbPass:
    secretKey:


imagePullSecret:
  enabled: true
  name: ecr-secret
  dockerconfigjson: "" 
