apiVersion: v1
kind: Secret
metadata:
  name: forgejo-secrets
type: Opaque
stringData:
  FORGEJO_DB_USER: {{ .Values.forgejo.credentials.dbUser }}
  FORGEJO_DB_PASS: {{ .Values.forgejo.credentials.dbPass }}
  FORGEJO_SECRET_KEY: {{ .Values.forgejo.credentials.secretKey }}
